;))))))))

diff --git a/bazelw b/bazelw
--- a/bazelw
+++ b/bazelw
@@ -14,15 +14,15 @@ else
     exit 1
 fi
 
-echo "installing bazel@${bazel_version} for ${bazel_platform}"
+echo "using bazel@${bazel_version} for ${bazel_platform}"
 
 readonly bazel_version_url="https://github.com/bazelbuild/bazel/releases/download/$bazel_version/bazel-$bazel_version-$bazel_platform-x86_64"
 readonly script_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
-readonly bazel_root="$script_root/tmp/bazel/versions/$bazel_version-$bazel_platform"
+readonly bazel_root="$script_root/out/bazel/versions/$bazel_version-$bazel_platform"
 readonly bazel_executable="$bazel_root/bin/bazel"
 
 if [[ ! -x "$bazel_executable" ]]; then
-  echo "Installing bazel..." >&2
+  echo "could not find a cached installation, downloading bazel..." >&2
   mkdir -p "$(dirname "$bazel_executable")"
   extra_curl_args=""
   if [[ -n "${BUILD_BUILDID:-}" ]]; then
